version: '3.2'

services:
   db:
      image: mysql:8.0
      container_name: appsDB
      restart: always
      ports:
         - '3306:3306'
      expose:
         - '3306'
      environment:
         MYSQL_ROOT_PASSWORD: password
      volumes:
         - my-db:/var/lib/mysql
   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8081:80'
      environment:
        PMA_HOST: db

volumes:
   my-db: